# -*- coding: utf-8 -*-
"""minerando-dados-unitins.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CsGJ5vCjPrOqCT8ZaGUi8OS39hG2qjB4
"""

import pandas as pd

url = "https://www.unitins.br/portaltransparencia/folha-de-pagamento?TipoAno=2021&tipoMes=02&TipoPesquisa=Nome&busca="
salario = pd.read_html(url)

df = pd.DataFrame(salario[0])

# df.head()

print("Total de servidores: ", len(df))
print("Total de efetivos: ", len(df[df['VÍNCULO'] == 'EFETIVO']))
print("Total de comissionados: ", len(df[df['VÍNCULO'] == 'COMISSIONADO']))
print("Total de contratados: ", len(df[df['VÍNCULO'] == 'CONTRATADO']))
print("Total de a disposição: ", len(df[df['VÍNCULO'] == 'EFETIVO/Disp']))

profs = ['PROF. ADJUNTO I', 'PROF. DOUTOR I /2893', 'PROF. MESTRE I /2893', 
         'PROF.UNIVERSITARIO 2','PROF UNIVERSITARIO 3', 'PROF UNIVERSITARIO I', 
         'QS PU1PROF ESP. 4','QS PU1PROF, DOUTOR4', 'QS PUI PROF, MESTRE 4']

#filtro_prof_efetivos = (df['FUNÇÃO']. isin(profs)) & (df['VÍNCULO'] == 'EFETIVO')

tiposProfessores = df['VÍNCULO'].unique()

def formatarSalario(salario):
    salario = salario.replace('R$', '').replace('.', '').replace(',', '.')
    return float(salario.strip())

for professor in profs:
      for tipoProfessor in tiposProfessores:
          filtro = (df['FUNÇÃO'] == professor) & (df['VÍNCULO'] == tipoProfessor)
          df_filtro = df[filtro]

          if not df_filtro.empty:
              print('{} | {}'.format(professor, tipoProfessor))
              for i in df_filtro.index:
                      df_filtro['SALÁRIO LÍQUIDO'][i] = formatarSalario(df_filtro['SALÁRIO LÍQUIDO'][i])

              print('Quantidade de Professores: {}'.format(len(df_filtro['SALÁRIO LÍQUIDO'])))
              print('Maior salário: {}'.format(df_filtro['SALÁRIO LÍQUIDO'].max()))
              print('Menor salário: {}'.format(df_filtro['SALÁRIO LÍQUIDO'].min()))
              print('Média salarial: {}'.format(df_filtro['SALÁRIO LÍQUIDO'].mean()))
              print('\n')